### ISSUE TITLE
Calculate statistics based on selections

### ISSUE THREAD

**Issue by anjase** [sondre99v/ShutEye#6]
- Total number of selections
- Total number of selection in each sleep stage
- Proportion of each sleep stage covered by selections
- Proportion of total sleep covered by selections
- Number of times each channel is highlighted in a selection
- Average: lenght, highlighted and average frequency, highlighted and average amplitude
  - In total
  - For each sleep stage

**Comment by sondre99v** [comment]
The statistics that are exported by "spindelvisning.m" has been implemented. Further statistics will be postponed to future improvements.
